description: |
  German caps_word behavior that capitalizes umlauts

compatible: "zmk,behavior-caps-word-de"

properties:
  label:
    type: string
    required: true
  continue-list:
    type: array
    default: [DE_UNDERSCORE, DE_MINUS, DE_A_UMLAUT, DE_U_UMLAUT, DE_O_UMLAUT]

binding-cells: [0]
