---
include:
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart   # Comment to log over USB.
    #snippet: zmk-usb-logging      # Uncomment to log over USB.
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: left_eyelash_corne
  - board: eyelash_corne_right
    shield: nice_view
    artifact-name: right_eyelash_corne
  - board: eyelash_corne_left
    shield: settings_reset
    artifact-name: settings_reset_eyelash_corne
 
